-- 0001_auth.sql — freemium auth/payments schema (AUTH_PLAN.md §5)
--
-- Requires Neon Auth + Data API enabled on the branch FIRST: this script
-- depends on the `authenticated` role and the `auth.user_id()` helper, both
-- provisioned by enabling Auth + the Data API. Run `npm run db:migrate`.
-- After applying, refresh the Data API schema cache (AUTH_PLAN.md §3).

-- ============ saved_scenarios: full CRUD over OWN rows (Free-tier feature) ============
create table public.saved_scenarios (
  id        bigint generated by default as identity primary key,
  user_id   text not null default (auth.user_id()),
  name      text not null,
  state     jsonb not null,                       -- a SerializedState blob (AUTH_PLAN.md §1)
  saved_at  timestamptz not null default now()
);
alter table public.saved_scenarios enable row level security;

create policy manage_own_scenarios on public.saved_scenarios
  for all to authenticated
  using (auth.user_id() = user_id)
  with check (auth.user_id() = user_id);

create index saved_scenarios_user_idx on public.saved_scenarios (user_id, saved_at desc);

-- ============ user_profiles: client may READ its own row ONLY ============
-- No write policy => RLS denies all client writes. subscription_status and
-- stripe_customer_id are written solely by the Stripe functions over a direct
-- DATABASE_URL connection (bypasses RLS). See AUTH_PLAN.md §4 rule 1.
create table public.user_profiles (
  user_id             text primary key default (auth.user_id()),
  subscription_status text not null default 'free',   -- 'free' | 'pro'
  stripe_customer_id  text,
  created_at          timestamptz not null default now()
);
alter table public.user_profiles enable row level security;

create policy read_own_profile on public.user_profiles
  for select to authenticated
  using (auth.user_id() = user_id);

-- Defense in depth (RLS already blocks writes with no write policy):
revoke insert, update, delete on public.user_profiles from authenticated;
